// @generated by Studio Editor
export type StudioVector3 = [number, number, number];

export type StudioTransform = {
  position: StudioVector3;
  rotation: StudioVector3;
  scale: StudioVector3;
};

export type StudioLayout = {
  bookshelf: StudioTransform;
  deskArea: StudioTransform;
  upperFloorLeft: StudioTransform;
  upperFloorRight: StudioTransform;
  stairs: StudioTransform;
  backWall: StudioTransform;
  windowWall: StudioTransform;
};

export const studioLayout = {
  "bookshelf": {
    "position": [
      -2.82,
      0.8699999999999999,
      -3.18
    ],
    "rotation": [
      0,
      0,
      0
    ],
    "scale": [
      1,
      1,
      1
    ]
  },
  "deskArea": {
    "position": [
      -2.35,
      0.049999999999999996,
      0.1
    ],
    "rotation": [
      0,
      0,
      0
    ],
    "scale": [
      1,
      1,
      1
    ]
  },
  "upperFloorLeft": {
    "position": [
      -0.65,
      0,
      -2.55
    ],
    "rotation": [
      0,
      0,
      0
    ],
    "scale": [
      1,
      1,
      1
    ]
  },
  "upperFloorRight": {
    "position": [
      2.65,
      0,
      -2.54
    ],
    "rotation": [
      0,
      0,
      0
    ],
    "scale": [
      1.13,
      1,
      1
    ]
  },
  "stairs": {
    "position": [
      1.85,
      0,
      -1.05
    ],
    "rotation": [
      0,
      0,
      0
    ],
    "scale": [
      1,
      1,
      1
    ]
  },
  "backWall": {
    "position": [
      -0.1,
      2.08,
      -4.03
    ],
    "rotation": [
      0,
      0,
      0
    ],
    "scale": [
      1.02,
      1.09,
      1
    ]
  },
  "windowWall": {
    "position": [
      -4.21,
      2.077,
      -0.42
    ],
    "rotation": [
      0,
      0,
      0
    ],
    "scale": [
      1,
      1.09,
      1.02
    ]
  }
} satisfies StudioLayout;
